apiVersion: v1
kind: Pod
metadata:
  name: greetings
  labels:
    name: greetings
spec:
  containers:
    - image: gcr.io/cloud-computing-hw3-jiayi/greetings:v13
      name: greetpod
      ports:
      - containerPort: 5000
      env:
        - name: "PASSWORD"
          value: testpass123!@#
        - name: "DB"
          value: testdb
        - name: "HOST"
          value: 35.188.69.87
        - name: "USER"
          value: root